document_chunking:
    chunk_size: 1000
    chunk_overlap: 0
env_path: "../env/llm.env"
llm_embedding_model: "mxbai-embed-large"
llm_chat_model: "mistral-small-latest"
retriever:
    k: 5
    score_threshold: 0.2